ktor {
    deployment {
        port = 8080
        port = ${?KTOR_PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ codes.chirag.emailclient.server.ApplicationKt.module ]
    }
}

jwt {
    secret = "change-me-in-production"
    secret = ${?JWT_SECRET}
    audience = "http://0.0.0.0:8080"
    audience = ${?JWT_AUDIENCE}
    domain = "https://jwt-provider-domain/"
    domain = ${?JWT_DOMAIN}
    realm = "ktor sample app"
    realm = ${?JWT_REALITY}
    expiryMillis = 3600000
    expiryMillis = ${?JWT_EXPIRY_MILLIS}
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/emailclient"
    jdbcUrl = ${?DB_JDBC_URL}
    username = "postgres"
    username = ${?DB_USERNAME}
    password = "password"
    password = ${?DB_PASSWORD}
    maximumPoolSize = 3
    maximumPoolSize = ${?DB_MAX_POOL_SIZE}
}
