ktor {
    deployment {
        port = 8080
        port = ${?KTOR_PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ codes.chirag.emailclient.server.ApplicationKt.module ]
    }
}
